### ISSUE TITLE
Create basic tests for front and showcase page

### ISSUE THREAD

**Issue by zelima** [datopian/datahub-frontend#1]
We need basic tests to be sure that pages are up and working fine. We can transform the test written in python for dpr-api int JS

## Acceptance Criteria

- [x] Front page tested
- [x] Showcase page tested

## Tasks

- [x] write tests using mocha

**Comment by zelima** [comment]
FIXED
