### ISSUE TITLE
Outstanding items for showcase page

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datahub-frontend#15]
We have some outstanding items todo in showcase page:

* avatar - atm, it's hardcoded. What we want: 
  * to use images from gravatar.com
  * if not set then use our default image
* create mock data package for testing sizes, created and updated dates:
  * display size and date in human readable format

## Tasks

* [x] republish co2-ppm package under my own account
* [x] edit `datapackage.json` adding actual `size` of each resource and size of data package
  * [x] also add `created` and `updated` dates in ISO
  * [x] also add `owner` property that is an object with `email` (hash) and `username` properties
* [x] implement `bytes` library for displaying sizes
* [x] show avatar on showcase page using email hash of a user
  * [x] if there is no hash provided show our default image

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datopian/datahub-frontend/commit/776bc4960f110bb1dae77eaad11f58136b031410 and https://github.com/datopian/datahub-frontend/commit/827506171dc29289f388c8e80baa5a2d8ef48b35
