### ISSUE TITLE
New design for the front page

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datahub-frontend#16]
We want to redesign current front page. Mockup for a new design:

<img width="264" alt="screen shot 2017-06-25 at 19 07 24" src="https://user-images.githubusercontent.com/17809581/27518177-959b5ee0-59d9-11e7-9af0-eb6963c5bfc6.png">

## Acceptance criteria

* [x] to look like on the mockup
* [x] popular packages setup
* [x] tutorial packages setup

## Tasks

* [x] refactor config to have packages to show on front page
* [x] create functions to get list of packages + tests
* [x] refactor route for home page to pass list of packages
* [x] refactor `home.html` to implement new design

**Comment by anuveyatsu** [comment]
FIXED in #17 and https://github.com/datopian/datahub-frontend/commit/a96522f309af0b41429c3f3ebc431839a152ce1b
