### ISSUE TITLE
Login using conductor

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datahub-frontend#18]
Implement a new login flow using os-conductor.

## Acceptance criteria

* [x] I can login using my GitHub (or Google) account
* [x] I can see my dashboard page instead of home page

## Tasks

* [x] analysis
* [x] function that handles authentication
  * [x] makes call to `https://datax.phonaris.com/auth/check` with token
  * [x] if authenticated - redirects to main page (dashboard)
  * [x] if not takes appropriate url from response and makes a call
  * [x] received token is stored in cookies and client is redirected to home page
* [x] setup routes for login
* [x] base url setup correctly
* [x] logout process
  * [x] redirect to home page saying user was logged out
* [x] small tweaks on home.html, base.html for navbar

## Analysis

* make a call to `https://datax.phonaris.com/auth/check?next=https:/some-base-url.com/success`
  * also can set `jwt=...` query
    * if authenticated - response body would include user info
    * not authenticated - response body would include urls for login by providers (github, google etc.)

**Comment by anuveyatsu** [comment]
FIXED in #19
