### ISSUE TITLE
Lint the application

### ISSUE THREAD

**Issue by zelima** [datopian/datahub-frontend#4]
We need beautiful and easily readable code for our app. We can use https://github.com/sindresorhus/xo 

## Acceptance criteria

- [x] code is under Lint
- [x] check on every PR

## Tasks

- [x] setup config
- [x] modify travis to run lin

**Comment by zelima** [comment]
FIXED
