### ISSUE TITLE
Showcase page ported

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-frontend#7]
## Acceptance criteria

* [x] Showcase page renders for /core/finance-vix

## Tasks

* [x] port template
* [x] load data package info from bitstore
* [x] port special markdown processor for README (with tests)
* [x] readme short
* [x] port dpr-js in
* [x] tests

**Comment by zelima** [comment]
FIXED
