### ISSUE TITLE
Travis is failing with Resolution method is overspecified

### ISSUE THREAD

**Issue by zelima** [datopian/datahub-frontend#8]
Mocha are failing on Travis with  
```
Lib Gets datapackage.json:
     Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.
      at it (tests/lib.test.js:17:5)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)
```

## Acceptance criteria 

- [x] tests are passing

## Tasks

- [x] Finde the reason/solution
- [x] remove done() from async functions
- [x] remove `node 6` from travis

Following this answer https://stackoverflow.com/a/41761748  calling done is redundant so we need to remove it.

Also tests are failing for node 6  as it does not support `async / await`. So for now think will be simplest to remove it at all

**Comment by zelima** [comment]
FIXED
